#! /bin/bash
# Copyright (c) 1996-2012 My Company.
# All rights reserved.
#
# Author: Bob Bobson, 2012
#
# Please send feedback to bob@bob.com
#
# /etc/init.d/testdaemon
#
### BEGIN INIT INFO
# Provides: controld
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  2
# Default-Stop:   0 1 3 4 5 6
# Short-Description: controld daemon process
# Description:    Runs up the test daemon process
### END INIT INFO

# Activate the python virtual environment
#    . /path_to_virtualenv/activate

PYTHON=python
DAEMON=/usr/share/testdaemon/testdaemon.py
NAME=controld

case "$1" in
  start)
    echo "Starting $NAME"
    $PYTHON $DAEMON start
    ;;
  stop)
    echo "Stopping $NAME"
    $PYTHON $DAEMON stop
    ;;
  restart)
    echo "Restarting $NAME"
    $PYTHON $DAEMON restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: $NAME {start|stop|restart}"
    exit 1
    ;;
esac

exit 0