#! /bin/bash
### BEGIN INIT INFO
# Provides: controld
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: controld daemon process
# Description: Runs up the controld daemon process
### END INIT INFO

# Activate the python virtual environment
# . /path_to_virtualenv/activate

/opt/controld/controld.py $1
exit $?